### ISSUE TITLE
Music not playing | There was an error while searching

### ISSUE THREAD

**Issue by ZagroCore** [wtfnotavailable/Discord-MusicBot#213] opened 2024-03-09 00:20 UTC
```sh
djs-bot    | [09.03.2024 - 00:19] [WARN ] | Player: 639536232438693888 | A music player has been created in Kurdîvan
lavalink   | 2024-03-09 00:19:17.415  INFO 1 --- [   XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"639536232438693888","volume":100}
lavalink   | 2024-03-09 00:19:17.416  WARN 1 --- [   XNIO-1 I/O-7] lavalink.server.io.WebSocketHandler      : Sending websocket commands to Lavalink has been deprecated and will b API version 3 will be removed in Lavalink 5. Please use the new REST endpoints instead.
lavalink   | 2024-03-09 00:19:17.615  INFO 1 --- [   XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op":"voiceUpdate","guildId":"639536232438693888","sessionId":"30b07","event":{"token":"ac8e5e5089b4dbd0","guild_id":"639536232438693888","endpoint":"rotterdam7930.discord.media:443"}}
lavalink   | 2024-03-09 00:19:18.035  INFO 1 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "ytsearch:eminem"
lavalink   | 2024-03-09 00:19:18.140 ERROR 1 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item ytsearch:eminem
lavalink   |
lavalink   | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
lavalink   |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:202) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:191) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink   |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavalink   |   lavaplayer.version: 1.5.2
lavalink   |   os.arch: amd64
lavalink   |   os.name: Linux
lavalink   |   os.version: 5.15.0-97-generic
lavalink   |   java.vendor: Eclipse Adoptium
lavalink   |   java.version: 18.0.2.1
lavalink   |   java.runtime.version: 18.0.2.1+1
lavalink   |   java.vm.version: 18.0.2.1+1
lavalink   | Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for search response: 400
lavalink   |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:59) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:70) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:284) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:250) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:38) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    ... 4 common frames omitted
lavalink   | Caused by: java.io.IOException: Invalid status code for search response: 400
lavalink   |    at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:62) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    ... 12 common frames omitted
lavalink   |
lavalink   | 2024-03-09 00:19:18.141 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed
lavalink   |
lavalink   | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
lavalink   |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:202) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:191) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink   |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavalink   |   lavaplayer.version: 1.5.2
lavalink   |   os.arch: amd64
lavalink   |   os.name: Linux
lavalink   |   os.version: 5.15.0-97-generic
lavalink   |   java.vendor: Eclipse Adoptium
lavalink   |   java.version: 18.0.2.1
lavalink   |   java.runtime.version: 18.0.2.1+1
lavalink   |   java.vm.version: 18.0.2.1+1
lavalink   | Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for search response: 400
lavalink   |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:59) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:70) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:284) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.search(YoutubeAudioSourceManager.java:250) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:38) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    ... 4 common frames omitted
lavalink   | Caused by: java.io.IOException: Invalid status code for search response: 400
lavalink   |    at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSearchProvider.loadSearchResult(YoutubeSearchProvider.java:62) ~[lavaplayer-1.5.2.jar!/:na]
lavalink   |    ... 12 common frames omitted
lavalink   |
lavalink   | 2024-03-09 00:19:18.506  INFO 1 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /loadtracks?identifier=ytsearch%3Aeminem, client=172.18.0.5
lavalink   | 2024-03-09 00:19:18.509  INFO 1 --- [   XNIO-1 I/O-7] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"639536232438693888"}
djs-bot    | [09.03.2024 - 00:19] [WARN ] | Player: 639536232438693888 | A music player has been destroyed in Kurdîvan
djs-bot    | [09.03.2024 - 00:19] [ERROR] | [FATAL] Possibly Unhandled Rejection
djs-bot    |    Reason: TypeError: Cannot read properties of undefined (reading 'logger')
djs-bot    |
djs-bot    | Promise {
djs-bot    |   <rejected> TypeError: Cannot read properties of undefined (reading 'logger')
djs-bot    |       at warn (/djs-bot/lib/Bot.js:72:8)
djs-bot    |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
djs-bot    | }

```

**Comment by ZagroCore** [comment] 2024-03-09 00:35
```sh
[09.03.2024 - 00:33] [WARN ] | Loading error handlers...
[09.03.2024 - 00:33] [ERROR] | Error handlers inhibited!
[09.03.2024 - 00:33] [DEBUG] | Music engine "Erela" has been loaded
[09.03.2024 - 00:33] [ERROR] | Prisma ORM failed to load
[09.03.2024 - 00:33] [ERROR] | Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report
[09.03.2024 - 00:33] [INFO ] | Slash commands have been loaded. Waiting for bot to finish initializing...
(node:139) [FSTWRN002] FastifyWarning: The routes plugin being registered mixes async and callback styles, which will result in an error in `fastify@5`
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by baskwo** [comment] 2024-03-09 06:28
Seems like lavaplayer has an open issue (https://github.com/lavalink-devs/lavaplayer/issues/69).

It also seems you can use lavalink:fix-yt-400-v3 instead of lavalink:3 in docker to fix it.

**Comment by LewdHuTao** [comment] 2024-03-09 07:34
Duplicate of #208. You can refer there to fix the issue and I'll close this. Feel free to reopen if you still have the issue.

**Comment by LewdHuTao** [comment] 2024-03-09 07:37
> It also seems you can use lavalink:fix-yt-400-v3 instead of lavalink:3 in docker to fix it.

Yes use lavalink:fix-yt-400-v3 fix the issue but temporary. You might need to keep an eye until they release new version that really fix this issue

**Closed as completed by LewdHuTao** 2024-03-09 07:37 UTC

**Comment by saher228** [comment] 2024-03-09 12:17
I posted a ready-made fix on v4 and v3. Use it!


https://github.com/saher228/fix-lavalink-404/releases/tag/fix
