### ISSUE TITLE
Update to Lavalink 4.x server

### ISSUE THREAD

**Issue by ngearhart** [wtfnotavailable/Discord-MusicBot#228] opened 2024-04-07 18:26 UTC
The bot as it exists today does not support Lavalink 4.x, only 3.x. Unfortunately, 3.x is not as actively updated as 4.x. Already, issues like https://github.com/lavalink-devs/Lavalink/issues/1030 are affecting me and will likely not be ported to 3.x.

**Comment by LewdHuTao** [comment] 2024-04-07 21:45
Wdym lavalink v3 isn't actively update? Everyone who uses lavalink v4 also get the same issue like the link you sent. They do have a new jar for both lavalink v3 and v4 that fixed that issue. You can find the latest jar on github or on lavalink discord server.

![Screenshot_2024_0408_054214](https://github.com/wtfnotavailable/Discord-MusicBot/assets/90232327/65cb4e91-dc01-45ad-b62b-e7e122ae51c6)

**Comment by LewdHuTao** [comment] 2024-04-07 21:45
Also duplicate of #223

**Closed as not planned** 2024-04-07 21:45 UTC
